## Put comments here that give an overall description of what your
## functions do

# return a datastructure which contains methods to set/get value and cache with
# value and cache stored in closure enviornment
makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    get <- function() {
        x        
    }
    setInverse <- function(inv) {
        i <<- inv
    }
    
    getInverse <- function(){
        i
    }
    
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


# return inverse of X$get from either cache (prefered) 
# or calculate it and cache for future use
# where x is expected to be a list generated by makeCacheMatrix()
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    i <- x$getInverse()
    if (!is.null(i)) {
        message('getting cache data')
        return(i)
    }
    
    data <- x$get()
    i <- solve(data, ...)
    x$setInverse(i)
    i
}
